export const USER_LIGGED_IN_TYPE  = 'USER_LIGGED_IN'
export const USER_LIGGED_OUT_TYPE = 'USER_LIGGED_OUT'

export const ADD_TO_BASKET = 'ADD_TO_BASKET'


export const FETCH_MEN_PRODUCTS   = 'FETCH_MEN_PRODUCTS'
export const FETCH_WOMEN_PRODUCTS = 'FETCH_WOMEN_PRODUCTS'


export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE'